version: '3.9'

services:
  server:
    container_name: server
    build: .
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "4008:4008"
    expose:
      - 4008
    volumes:
      - .:/src

  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    tty: true
    healthcheck:
      test: "exit 0"

  database:
    container_name: database
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'MultiMarket'
      MYSQL_ROOT_PASSWORD: 'password'
    tty: true
    healthcheck:
      test: "exit 0"
